//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTI_Booking_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookMethod
    {
        public int id { get; set; }
        public string Prefix { get; set; }
        public string SCAC { get; set; }
        public string BookingMethod { get; set; }
        public string OPSPIC { get; set; }
        public string PreAsign { get; set; }
        public string OPSName { get; set; }
        public string OPSTel { get; set; }
    
        public virtual forecast_carrierCode forecast_carrierCode { get; set; }
    }
}
