//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTI_Booking_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrierAgentList
    {
        public int id { get; set; }
        public string CarrierAgentCode { get; set; }
        public string Prefix { get; set; }
        public string CarrierAgentName { get; set; }
    }
}
