//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTI_Booking_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientDetail()
        {
            this.ClientLists = new HashSet<ClientList>();
            this.forecast_list = new HashSet<forecast_list>();
        }
    
        public int id { get; set; }
        public string Client { get; set; }
        public string TLUID { get; set; }
        public string Team { get; set; }
        public string Dept { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientList> ClientLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<forecast_list> forecast_list { get; set; }
    }
}
