//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTI_Booking_Platform.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForecastEntities : DbContext
    {
        public ForecastEntities()
            : base("name=ForecastEntities")
        {
            //this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookMethod> BookMethods { get; set; }
        public virtual DbSet<ClientDetail> ClientDetails { get; set; }
        public virtual DbSet<ClientList> ClientLists { get; set; }
        public virtual DbSet<forecast_carrierCode> forecast_carrierCode { get; set; }
        public virtual DbSet<forecast_list> forecast_list { get; set; }
        public virtual DbSet<forecast_portCode> forecast_portCode { get; set; }
        public virtual DbSet<BrokerList> BrokerLists { get; set; }
        public virtual DbSet<COList> COLists { get; set; }
        public virtual DbSet<MLOGEntityList> MLOGEntityLists { get; set; }
        public virtual DbSet<SHList> SHLists { get; set; }
        public virtual DbSet<WHSList> WHSLists { get; set; }
        public virtual DbSet<CarrierAgentList> CarrierAgentLists { get; set; }
    }
}
